### ISSUE TITLE
JavaScriptをjsファイルに分割する

### ISSUE THREAD

**Issue by TomoakiTANAKA** [ryou-kuzuno/LibraryApp#8]
## なぜ？
* javascriptのコードがhtml（erb）に直書きされているので見通しが悪い
* コードの役割に応じて、ファイルを適切に分割するべき

## やること
- [ ] erbに記述されているjsの機能を、*.jsに移す

**Comment by ryou-kuzuno** [comment]
分割に成功しました。

ただ問題が二つあります
1   jsファイルがgit add .に含まれず、コードを送れていない
2 コメントの<%%>を外したままになっている

２の方はすぐに終わりますが１の問題は少し調べただけでは解決しないのでまた調べてみます。
（チュートリアルが今の優先事項なためです）

おそらく伝達は以上です
